# -*- coding: utf-8 -*-
"""Peluang Keberuntungan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RCToderPauk_y1iSPPNe_ho2UynPItej
"""
import streamlit as st
import matplotlib.pyplot as plt
import numpy as np
import time

def calculate_probability(event_occurrences, total_outcomes):
    """Menghitung peluang suatu kejadian."""
    if total_outcomes <= 0:
        return 0.0, "Total kemungkinan hasil harus lebih dari nol."
    if event_occurrences < 0:
        return 0.0, "Jumlah kejadian yang diinginkan tidak boleh negatif."
    if event_occurrences > total_outcomes:
        return 0.0, "Jumlah kejadian yang diinginkan tidak boleh melebihi total kemungkinan hasil."

    probability = event_occurrences / total_outcomes
    return probability, None

def plot_probability_animation(probability):
    """Membuat animasi sederhana berupa bar chart untuk visualisasi peluang."""
    fig, ax = plt.subplots(figsize=(6, 2))
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_xticks([0, 0.25, 0.5, 0.75, 1])
    ax.set_yticks([])
    ax.set_title("Visualisasi Peluang")
    ax.set_xlabel("Peluang")

    bar = ax.barh(0.5, 0, height=0.4, color='skyblue')

    progress_text = st.empty()
    for i in range(1, 11):
        current_width = probability * (i / 10)
        bar[0].set_width(current_width)
        progress_text.text(f"Animasi: {int(current_width * 100)}%")
        # Menggunakan st.pyplot() langsung untuk menampilkan dan memperbarui plot
        st.pyplot(fig)
        time.sleep(0.1)

    plt.close(fig) # Penting untuk menutup figure agar tidak memakan memori

# Streamlit UI
st.set_page_config(page_title="Kalkulator Peluang Sederhana", layout="centered")

st.title("Kalkulator Peluang Sederhana")

st.write("""
Selamat datang di Kalkulator Peluang!
Masukkan jumlah kejadian yang diinginkan dan total kemungkinan hasil untuk menghitung peluangnya.
""")

# Input fields
st.header("Input Data")
event_occurrences = st.number_input(
    "Jumlah Kejadian yang Diinginkan:",
    min_value=0,
    value=1,
    step=1,
    help="Berapa kali kejadian yang Anda minati dapat terjadi."
)

total_outcomes = st.number_input(
    "Total Kemungkinan Hasil:",
    min_value=1,
    value=2,
    step=1,
    help="Total semua hasil yang mungkin terjadi dalam sebuah percobaan."
)

# Tombol untuk menghitung peluang
if st.button("Hitung Peluang"):
    st.subheader("Hasil Perhitungan")
    probability, error = calculate_probability(event_occurrences, total_outcomes)

    if error:
        st.error(f"Terjadi kesalahan: {error}")
    else:
        st.success(f"Peluang kejadian adalah: **{probability:.4f}**")
        st.info(f"Dalam persentase: **{probability * 100:.2f}%**")

        st.subheader("Animasi Visualisasi Peluang")
        plot_probability_animation(probability) # Memanggil fungsi animasi

st.markdown("---")
st.write("Dibuat dengan ❤️ menggunakan Streamlit")
